/** Framework 10 bước — AI hỗ trợ viết (dialog Trợ lý viết) */
export const WRITING_FLOW_STEPS: {
  id: string
  number: number
  title: string
  aiSupport: string[]
  authorProvides: string
  insertHtml: string
}[] = [
  { id: "problem", number: 1, title: "Xác định vấn đề đề tài", aiSupport: ["Soạn bối cảnh theo cấu trúc từ rộng đến hẹp.", "Viết problem statement ngắn và dài.", "Xây dựng mục tiêu và câu hỏi theo chuẩn SMART.", "Gợi ý cách xác định phạm vi, đối tượng, biến số/khái niệm chính."], authorProvides: "Chủ đề, bối cảnh, đối tượng và khoảng trống nhận thấy.", insertHtml: `<h2>1. Xác định vấn đề đề tài</h2><h3>1.1. Bối cảnh</h3><p><br></p><h3>1.2. Problem statement</h3><p><br></p><h3>1.3. Mục tiêu và câu hỏi (SMART)</h3><p><br></p><h3>1.4. Phạm vi, đối tượng và biến số/khái niệm</h3><p><br></p><p><br></p>` },
  { id: "literature", number: 2, title: "Tổng quan tài liệu (Literature Review)", aiSupport: ["Tạo dàn ý literature review theo chủ đề, mô hình hoặc phương pháp.", "Viết các đoạn tổng hợp (synthesis) thay vì liệt kê.", "Xây dựng bảng so sánh các công trình trước.", "Soạn khoảng trống (literature gap) rõ ràng để dẫn đến RQ hoặc giả thuyết."], authorProvides: "Danh sách bài báo hoặc ý chính cần tổng hợp.", insertHtml: `<h2>2. Tổng quan tài liệu</h2><h3>2.1. Dàn ý và tổng hợp</h3><p><br></p><h3>2.2. Bảng so sánh các công trình trước</h3><p><br></p><h3>2.3. Khoảng trống (literature gap)</h3><p><br></p><p><br></p>` },
  { id: "rq", number: 3, title: "Câu hỏi và giả thuyết", aiSupport: ["Chuẩn hóa câu hỏi (RQ) theo dạng mô tả, quan hệ hoặc nhân quả.", "Viết hệ thống hypotheses và giải thích cơ sở lý thuyết.", "Soạn định nghĩa khái niệm và mô tả cách đo lường."], authorProvides: "Mục tiêu đề tài và các biến/khái niệm chính.", insertHtml: `<h2>3. Câu hỏi và giả thuyết</h2><h3>3.1. Câu hỏi (RQ)</h3><p><br></p><h3>3.2. Hypotheses / Propositions</h3><p><br></p><h3>3.3. Định nghĩa khái niệm và đo lường</h3><p><br></p><p><br></p>` },
  { id: "methodology", number: 4, title: "Phương pháp (Methodology)", aiSupport: ["Soạn phần thiết kế (Design) đúng văn phong học thuật.", "Mô tả sampling, công cụ đo lường, quy trình.", "Viết các đoạn về reliability, validity hoặc trustworthiness."], authorProvides: "Loại đề tài dự kiến (survey, experiment, case study…).", insertHtml: `<h2>4. Phương pháp</h2><h3>4.1. Thiết kế (Design)</h3><p><br></p><h3>4.2. Sampling và công cụ đo lường</h3><p><br></p><h3>4.3. Quy trình, reliability và validity</h3><p><br></p><p><br></p>` },
  { id: "collection", number: 5, title: "Thu thập dữ liệu", aiSupport: ["Kịch bản phỏng vấn bán cấu trúc.", "Phiếu khảo sát với phần giới thiệu, consent và thang đo.", "Protocol thực nghiệm và mô tả đạo đức."], authorProvides: "Loại dữ liệu, đối tượng tham gia và bối cảnh thực hiện.", insertHtml: `<h2>5. Thu thập dữ liệu</h2><h3>5.1. Quy trình và công cụ thu thập</h3><p><br></p><h3>5.2. Consent và đạo đức</h3><p><br></p><p><br></p>` },
  { id: "analysis", number: 6, title: "Phân tích dữ liệu", aiSupport: ["Analysis plan: phương pháp thống kê hoặc phân tích định tính phù hợp.", "Mô tả quy trình làm sạch dữ liệu và xử lý thiếu dữ liệu.", "Kế hoạch mã hóa dữ liệu định tính."], authorProvides: "Loại dữ liệu, câu hỏi đề tài và công cụ dự kiến sử dụng.", insertHtml: `<h2>6. Phân tích dữ liệu</h2><h3>6.1. Kế hoạch phân tích</h3><p><br></p><h3>6.2. Làm sạch dữ liệu và mã hóa</h3><p><br></p><p><br></p>` },
  { id: "results", number: 7, title: "Kết quả (Results)", aiSupport: ["Tường thuật kết quả dựa trên bảng hoặc hình do tác giả cung cấp.", "Viết chú thích bảng biểu và cấu trúc mục Results theo RQ/Hypothesis."], authorProvides: "Bảng số liệu, biểu đồ hoặc mô tả kết quả.", insertHtml: `<h2>7. Kết quả</h2><h3>7.1. Kết quả theo RQ/Hypothesis</h3><p><br></p><h3>7.2. Bảng và hình</h3><p><br></p><p><br></p>` },
  { id: "discussion", number: 8, title: "Thảo luận (Discussion)", aiSupport: ["Diễn giải ý nghĩa của kết quả.", "So sánh với các công trình trước.", "Viết phần implications, limitations và hướng tiếp theo."], authorProvides: "Các điểm nhấn chính và các công trình cần đối chiếu.", insertHtml: `<h2>8. Thảo luận</h2><h3>8.1. Diễn giải và so sánh</h3><p><br></p><h3>8.2. Implications, limitations và hướng tiếp theo</h3><p><br></p><p><br></p>` },
  { id: "conclusion", number: 9, title: "Kết luận và đóng góp", aiSupport: ["Tổng hợp phát hiện chính.", "Viết mục contributions theo chuẩn học thuật.", "Đề xuất hướng tiếp theo."], authorProvides: "Các phát hiện chính và đóng góp dự kiến.", insertHtml: `<h2>9. Kết luận</h2><h3>9.1. Tóm tắt phát hiện</h3><p><br></p><h3>9.2. Đóng góp</h3><p><br></p><h3>9.3. Hướng tiếp theo</h3><p><br></p><h2>Tài liệu tham khảo</h2><p><br></p><p><br></p>` },
  { id: "standardize", number: 10, title: "Công bố", aiSupport: ["Giúp bạn tạo checklist nộp bài và viết Cover letter.", "Chuẩn hóa giọng văn học thuật và cấu trúc lập luận.", "Viết abstract theo cấu trúc chuẩn.", "Rà soát tính logic và nhất quán thuật ngữ."], authorProvides: "Bản nháp hoặc nội dung cần chuẩn hóa; mục tiêu nộp bài.", insertHtml: `<h2>Công bố</h2><p><br></p><h3>Cover letter</h3><p><br></p><h3>Checklist nộp bài</h3><p><br></p><p><br></p>` },
]
